# Generated by Django 3.1 on 2022-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=55, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
